server:
  port: 13268

spring:
  application:
    name: qbserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/qbserver?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime:500000
  redis:
    host: localhost
    port: 6379
    database: 5
    password: 123456789
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s